[project]
name = "web-checker"
version = "1.0.0"
description = "The web application that checks a website's SEO score."
authors = [
    { name = "Thinh Nguyen Phuoc", email = "npthinh1996@gmail.com" }
]
license = { text = "GPL-3.0" }
readme = "README.md"
requires-python = "^3.10"
dependencies = [
    "Django (>=5.1,<5.2)",
    "lxml (>=5.3,<5.4)",
    "requests (>=2.32,<2.33)"
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
black = "~24.10"
coverage = "~7.6"

[tool.poetry.group.deploy.dependencies]
uvicorn = "~0.34"

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.coverage.run]
branch = true
omit = [
    "*/migrations/*",
    "src/*",
    "*/__init__.py",
    "*/tests.py",
    "manage.py",
]
source = ["."]

[tool.coverage.report]
skip_covered = false
skip_empty = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
